site_name: HiEasyX文档
site_url: https://hiex.netlify.app/
nav:
    - '主页': 'index.md'
    - '快速攻略': 
      - '快速入门': 'introduction\tutorial.md'
      - '快速基础': 
        - 'introduction\basic\index.md'
        - '窗口相关':
          - '绘图窗口基础': 'introduction\basic\wnd_basic.md'
          - '自定义窗口样式': 'introduction\basic\wnd_style.md'
          - '自定义程序图标': 'introduction\basic\wnd_icon.md'
          - '自定义窗口过程函数': 'introduction\basic\wnd_proc.md'
          - '创建托盘': 'introduction\basic\wnd_tray.md'
        - '绘图相关':
          - 'Canvas 画布绘图基础': 'introduction\basic\draw_basic.md'
          - '使用 Canvas 绑定窗口或 IMAGE 对象': 'introduction\basic\draw_bind.md'
          - '场景的使用': 'introduction\basic\draw_scene.md'
          - '使用封装的 GDI+ 接口绘图': 'introduction\basic\draw_gdiplus.md'
          - '使用基础 EasyX 函数绘制透明图形': 'introduction\basic\draw_tns.md'
        - '控件相关':
          - '使用封装的 Win32 控件': 'introduction\basic\ctrl_sys.md'
        - '常见问题': 'introduction\basic\qa.md'
        - '程序启动动画': 'introduction\basic\start_animation.md'
      - '配置 HiEasyX 专题': 
        - 'introduction\configure\index.md'
        - '新项目配置': 'introduction\configure\configure-new.md'
        - '迁移项目配置': 'introduction\configure\configure-transfer.md'
    - '基本概念':
      - 'concept\index.md'
      - '颜色': 'concept\color.md'
      - '坐标': 'concept\coordinate.md'
      - '设备': 'concept\equipment.md'
    - '函数说明':
      - 'function\index.md'
      - '窗口设置相关函数':
        - 'initgraph': 'function\window\initgraph.md'
        - 'initgraph_win32': 'function\window\initgraph_win32.md'
        - 'closegraph': 'function\window\closegraph.md'
        - 'closegraph_win32': 'function\window\closegraph_win32.md'
      - '绘图设置相关函数':
        - 'cleardevice': 'function\drawing\cleardevice.md'
        - 'getaspectratio': 'function\drawing\getaspectratio.md'
        - 'setaspectratio': 'function\drawing\setaspectratio.md'
        - 'graphdefaults': 'function\drawing\graphdefaults.md'
        - 'setorigin': 'function\drawing\setorigin.md'
        - 'setcliprgn': 'function\drawing\setcliprgn.md'
        - 'clearcliprgn': 'function\drawing\clearcliprgn.md'
    - '绘图库简介': 'intro.md'
    - '关于': 
      - '关于网站': 'about\about-website.md'
      - '贡献事项': 'about\contribution.md'
      - '离线使用及历史版本': 'about\history.md'
      - '提供反馈或建议': 'about\feedback.md'
theme:
  name: "material"
  custom_dir: overrides
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
  language: zh
  logo: favicon.png
  icon: 
    repo: fontawesome/brands/github
  favicon: favicon.png
extra:
  analytics:
    provider: custom
    property: foobar
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Alan-CRL/HiEasyX-docs
      name: HiEasyX文档 github 项目
copyright: HiEasyX文档 是无版权的开源项目
plugins:
  - search
  - offline
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
repo_url: https://github.com/Alan-CRL/HiEasyX-Docs
repo_name: Alan-CRL/HiEasyX-Docs
edit_uri: blob/main/docs/